"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase, type Vehicle } from "@vertice/core";

const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
export default function Home(){
 const [cars,setCars]=useState<Vehicle[]>([]),[category,setCategory]=useState("Todos"),[search,setSearch]=useState(""),[sent,setSent]=useState(false);
 useEffect(()=>{supabase().from("vehicles").select("*").eq("status","available").order("featured",{ascending:false}).then(({data})=>setCars((data||[]) as Vehicle[]))},[]);
 const shown=useMemo(()=>cars.filter(c=>(category==="Todos"||c.category===category)&&c.name.toLowerCase().includes(search.toLowerCase())),[cars,category,search]);
 async function lead(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase().from("leads").insert({name:f.get("name"),phone:f.get("phone"),email:f.get("email"),subject:f.get("subject"),source:"site"});if(!error){setSent(true);e.currentTarget.reset()}}
 return <main><div className="top">Mais de 80 veículos disponíveis <span>Segunda a sábado • (11) 3500-1234</span></div><header><b><i>V</i> VÉRTICE MOTORS</b><nav><a href="#estoque">Estoque</a><a href="#venda">Venda seu carro</a><a href="#financiamento">Financiamento</a><a href="#localizacao">Localização</a></nav><a className="button ghost" href="#contato">Fale conosco</a></header>
 <section className="hero"><div><small>SEU PRÓXIMO CAMINHO COMEÇA AQUI</small><h1>O carro certo para a sua próxima história.</h1><p>Veículos selecionados, procedência garantida e atendimento transparente do primeiro contato à entrega.</p><a className="button" href="#estoque">Ver veículos →</a></div></section>
 <section id="estoque" className="section"><small>NOSSO ESTOQUE</small><h2>Escolhidos para você dirigir tranquilo.</h2><div className="filters"><div>{["Todos","SUV","Sedã","Hatch","Picape"].map(x=><button className={category===x?"active":""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><input aria-label="Buscar veículo" placeholder="Buscar por modelo" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="grid">{shown.map(c=><article key={c.id}><div className="photo" style={c.cover_url?{backgroundImage:`url(${c.cover_url})`}:{}}><span>{c.featured?"Destaque":"Disponível"}</span></div><div className="car"><small>{c.year} • {c.mileage.toLocaleString("pt-BR")} km • {c.transmission}</small><h3>{c.name}</h3><p>A partir de</p><strong>{money(c.price)}</strong><a href="#contato">Tenho interesse →</a></div></article>)}</div>{cars.length===0&&<p className="empty">O estoque será exibido assim que os veículos forem cadastrados no painel.</p>}</section>
 <section id="venda" className="dark section"><div><small>VENDA SEU CARRO</small><h2>Uma avaliação justa, rápida e transparente.</h2><p>Cuidamos da vistoria, documentação e pagamento com segurança.</p></div><a className="button" href="#contato">Avaliar meu carro</a></section>
 <section id="financiamento" className="blue section"><div><small>FINANCIAMENTO</small><h2>Condições que cabem nos seus planos.</h2><p>Entrada flexível e prazo de até 60 meses.</p></div><a className="button ghost" href="#contato">Simular agora</a></section>
 <section id="localizacao" className="location section"><div className="map">⌖<b>Vértice Motors</b></div><div><small>NOSSA LOJA</small><h2>Venha conhecer seu próximo carro.</h2><p>Av. das Nações, 1250 — Vila Olímpia, São Paulo, SP</p><p>Segunda a sexta, 8h às 18h • Sábado, 8h às 16h</p><a className="button" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=Vila+Ol%C3%ADmpia+S%C3%A3o+Paulo">Abrir rota ↗</a></div></section>
 <section id="contato" className="contact section"><div><small>VAMOS CONVERSAR?</small><h2>Seu próximo carro está mais perto.</h2><p>Envie seus dados e nossa equipe entrará em contato.</p></div><form onSubmit={lead}><input name="name" required placeholder="Seu nome"/><input name="phone" required placeholder="WhatsApp"/><input name="email" type="email" placeholder="E-mail"/><select name="subject" required defaultValue=""><option value="" disabled>Assunto</option><option>Comprar um veículo</option><option>Vender meu carro</option><option>Financiamento</option></select><button className="button">Enviar mensagem</button>{sent&&<p className="success">Mensagem recebida. Em breve entraremos em contato!</p>}</form></section><footer><b>VÉRTICE MOTORS</b><span>Veículos selecionados. Negócios transparentes.</span></footer></main>
}
