"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase, type Lead, type Role, type UserStatus, type Vehicle } from "@vertice/core";

type Profile={id:string;email:string;full_name:string|null;role:Role;status:UserStatus;created_at:string};
type Finance={id:string;status:string;desired_entry:number|null;desired_term:number|null;monthly_income:number|null;created_at:string};
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});

export default function Admin(){
 const db=supabase(),[session,setSession]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[mode,setMode]=useState<"login"|"register">("login"),[tab,setTab]=useState("dashboard"),[error,setError]=useState(""),[loading,setLoading]=useState(true),[vehicles,setVehicles]=useState<Vehicle[]>([]),[leads,setLeads]=useState<Lead[]>([]),[finance,setFinance]=useState<Finance[]>([]),[users,setUsers]=useState<Profile[]>([]),[vehicleModal,setVehicleModal]=useState(false);
 useEffect(()=>{db.auth.getSession().then(({data})=>{if(data.session){setSession(true);loadProfile(data.session.user.id)}else setLoading(false)});const {data}=db.auth.onAuthStateChange((_e,s)=>{setSession(!!s);if(s)loadProfile(s.user.id);else{setProfile(null);setLoading(false)}});return()=>data.subscription.unsubscribe()},[]);
 async function loadProfile(id:string){const {data}=await db.from("profiles").select("*").eq("id",id).single();setProfile(data as Profile);setLoading(false);if(data?.status==="active")loadData()}
 async function loadData(){const [v,l,f,u]=await Promise.all([db.from("vehicles").select("*").order("created_at",{ascending:false}),db.from("leads").select("*").order("created_at",{ascending:false}),db.from("financing_requests").select("*").order("created_at",{ascending:false}),db.from("profiles").select("*").order("created_at",{ascending:false})]);setVehicles((v.data||[]) as Vehicle[]);setLeads((l.data||[]) as Lead[]);setFinance((f.data||[]) as Finance[]);setUsers((u.data||[]) as Profile[])}
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password"));if(mode==="login"){const {error}=await db.auth.signInWithPassword({email,password});if(error)setError("E-mail ou senha inválidos.")}else{const {error}=await db.auth.signUp({email,password,options:{data:{full_name:f.get("name")}}});setError(error?error.message:"Cadastro enviado. Aguarde a aprovação do administrador.")}}
 async function saveVehicle(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const row={name:f.get("name"),brand:f.get("brand"),model:f.get("model"),year:Number(f.get("year")),mileage:Number(f.get("mileage")),price:Number(f.get("price")),category:f.get("category"),transmission:f.get("transmission"),fuel:f.get("fuel"),color:f.get("color"),cover_url:f.get("cover_url")||null,status:f.get("status"),featured:f.get("featured")==="on",created_by:profile?.id};const {error}=await db.from("vehicles").insert(row);if(!error){setVehicleModal(false);loadData()}else setError(error.message)}
 async function update(table:string,id:string,values:Record<string,unknown>){await db.from(table).update(values).eq("id",id);loadData()}
 if(loading)return <div className="center"><div className="loader"/></div>;
 if(!session)return <main className="auth"><section><div className="logo"><i>V</i><b>VÉRTICE ADMIN</b></div><small>ACESSO RESTRITO</small><h1>{mode==="login"?"Bem-vindo de volta.":"Solicitar acesso."}</h1><p>{mode==="login"?"Entre com seu e-mail e senha autorizados.":"Seu cadastro ficará pendente até a aprovação de um administrador ou gerente."}</p><form onSubmit={auth}>{mode==="register"&&<input name="name" required placeholder="Nome completo"/>}<input name="email" type="email" required placeholder="E-mail"/><input name="password" type="password" minLength={8} required placeholder="Senha"/><button>Continuar</button></form>{error&&<p className="message">{error}</p>}<button className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Ainda não tenho acesso":"Voltar ao login"}</button></section><aside><span>Gestão inteligente</span><h2>Estoque, clientes e oportunidades em um só lugar.</h2></aside></main>;
 if(profile?.status!=="active")return <div className="pending"><div className="logo"><i>V</i><b>VÉRTICE ADMIN</b></div><span>⌛</span><h1>Acesso aguardando aprovação</h1><p>Seu cadastro foi recebido. Um administrador ou gerente precisa ativar sua conta.</p><button onClick={()=>db.auth.signOut()}>Sair</button></div>;
 const nav=[['dashboard','Visão geral'],['vehicles','Estoque'],['leads','Leads'],['finance','Financiamentos'],['users','Usuários']];
 return <main className="app"><aside className="sidebar"><div className="logo"><i>V</i><b>VÉRTICE</b></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="account"><b>{profile.full_name||profile.email}</b><span>{profile.role}</span><button onClick={()=>db.auth.signOut()}>Sair</button></div></aside><section className="content"><header><div><small>PAINEL ADMINISTRATIVO</small><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><button className="primary" onClick={()=>setVehicleModal(true)}>+ Novo veículo</button></header>
 {tab==='dashboard'&&<><div className="metrics"><article><span>Estoque disponível</span><b>{vehicles.filter(v=>v.status==='available').length}</b><small>{money(vehicles.filter(v=>v.status==='available').reduce((s,v)=>s+v.price,0))} em veículos</small></article><article><span>Novos leads</span><b>{leads.filter(l=>l.status==='new').length}</b><small>{leads.length} contatos no total</small></article><article><span>Financiamentos</span><b>{finance.filter(f=>f.status==='new').length}</b><small>Aguardando análise</small></article><article><span>Usuários pendentes</span><b>{users.filter(u=>u.status==='pending').length}</b><small>Requerem aprovação</small></article></div><div className="panel"><h2>Leads recentes</h2><LeadTable leads={leads.slice(0,5)} onUpdate={update}/></div></>}
 {tab==='vehicles'&&<div className="panel"><h2>Veículos cadastrados</h2><div className="table"><div className="tr head"><span>Veículo</span><span>Ano</span><span>Preço</span><span>Status</span><span>Ação</span></div>{vehicles.map(v=><div className="tr" key={v.id}><span><b>{v.name}</b><small>{v.mileage.toLocaleString('pt-BR')} km</small></span><span>{v.year}</span><span>{money(v.price)}</span><span><select value={v.status} onChange={e=>update('vehicles',v.id,{status:e.target.value})}><option value="draft">Rascunho</option><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></select></span><span><button className="danger" onClick={()=>update('vehicles',v.id,{status:'sold'})}>Marcar vendido</button></span></div>)}</div></div>}
 {tab==='leads'&&<div className="panel"><h2>Central de leads</h2><LeadTable leads={leads} onUpdate={update}/></div>}
 {tab==='finance'&&<div className="panel"><h2>Solicitações de financiamento</h2><div className="table"><div className="tr head"><span>Data</span><span>Entrada</span><span>Prazo</span><span>Renda</span><span>Status</span></div>{finance.map(f=><div className="tr" key={f.id}><span>{new Date(f.created_at).toLocaleDateString('pt-BR')}</span><span>{money(f.desired_entry||0)}</span><span>{f.desired_term||'—'} meses</span><span>{money(f.monthly_income||0)}</span><span><select value={f.status} onChange={e=>update('financing_requests',f.id,{status:e.target.value})}><option value="new">Novo</option><option value="review">Em análise</option><option value="approved">Aprovado</option><option value="rejected">Recusado</option></select></span></div>)}</div></div>}
 {tab==='users'&&<div className="panel"><h2>Usuários e permissões</h2><div className="table users"><div className="tr head"><span>Usuário</span><span>Função</span><span>Status</span><span>Cadastro</span><span>Ação</span></div>{users.map(u=><div className="tr" key={u.id}><span><b>{u.full_name||'Sem nome'}</b><small>{u.email}</small></span><span><select disabled={profile.role!=='admin'} value={u.role} onChange={e=>update('profiles',u.id,{role:e.target.value})}><option value="agent">Atendente</option><option value="manager">Gerente</option><option value="admin">Administrador</option></select></span><span className={`status ${u.status}`}>{u.status}</span><span>{new Date(u.created_at).toLocaleDateString('pt-BR')}</span><span><button onClick={()=>update('profiles',u.id,{status:u.status==='active'?'blocked':'active'})}>{u.status==='active'?'Bloquear':'Aprovar'}</button></span></div>)}</div></div>}
 </section>{vehicleModal&&<div className="backdrop"><form className="modal" onSubmit={saveVehicle}><button type="button" className="close" onClick={()=>setVehicleModal(false)}>×</button><h2>Novo veículo</h2><div className="fields"><input name="name" required placeholder="Nome completo do veículo"/><input name="brand" required placeholder="Marca"/><input name="model" required placeholder="Modelo"/><input name="year" required type="number" placeholder="Ano"/><input name="mileage" required type="number" placeholder="Quilometragem"/><input name="price" required type="number" placeholder="Preço"/><select name="category" required><option>SUV</option><option>Sedã</option><option>Hatch</option><option>Picape</option></select><select name="transmission"><option>Automático</option><option>Manual</option></select><input name="fuel" placeholder="Combustível"/><input name="color" placeholder="Cor"/><input name="cover_url" placeholder="URL da foto"/><select name="status"><option value="draft">Rascunho</option><option value="available">Disponível</option></select><label><input type="checkbox" name="featured"/> Veículo em destaque</label></div><button className="primary">Salvar veículo</button>{error&&<p className="message">{error}</p>}</form></div>}</main>
}
function LeadTable({leads,onUpdate}:{leads:Lead[];onUpdate:(table:string,id:string,values:Record<string,unknown>)=>void}){return <div className="table"><div className="tr head"><span>Contato</span><span>Assunto</span><span>Origem</span><span>Data</span><span>Status</span></div>{leads.map(l=><div className="tr" key={l.id}><span><b>{l.name}</b><small>{l.phone}</small></span><span>{l.subject}</span><span>{l.source}</span><span>{new Date(l.created_at).toLocaleDateString('pt-BR')}</span><span><select value={l.status} onChange={e=>onUpdate('leads',l.id,{status:e.target.value})}><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="won">Convertido</option><option value="lost">Perdido</option></select></span></div>)}</div>}
